:starter
SET ON
ON OPENERR
ON OPENERR GOTO telerr
# Set up TTY over IP.
set console telnet=2222;notelnet
set tti 8b
set tto 8b
ON OPENERR
! socat PTY,echo=0,link=ttyPDP TCP:localhost:2222 &
# Start CSD, configured for "ttyPDP".
#! ./csd -B -D &
! ./csd -B &

echo $$

# Now toggle in the bootstrap.
set cpu 4k
d 00025 6031
d 00026 5025
d 00027 6036
d 00030 7012
d 00031 7010
d 00032 3001
d 00033 2032
d 00034 5025
#br 353
run 25

goto done
:telerr
echo TTI has not released port. Retrying now...
! sleep 5
goto starter
:done
