# Set up TTY over IP.
set console telnet=2222;notelnet
! socat PTY,echo=0,link=ttyPDP TCP:localhost:2222 &
# Start CSD, configured for "ttyPDP".
! ./csd &
# Now toggle in the bootstrap.
d 00025 6031
d 00026 5025
d 00027 6036
d 00030 7012
d 00031 7010
d 00032 3001
d 00033 2032
d 00034 5025
#br 0-177;c
#set log foo.txt
set tti 8b
set tto 8b
show tti, tto
echo Press Shift-F12 to boot.
run 25
